services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: library-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: library-db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - library

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: library-redis
    ports:
      - "6379:6379"
    networks:
      - library

  node:
    build:
      context: .
    image: library-node
    container_name: library-node
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/app
    networks:
      - library
    ports:
      - "3000:3000"

volumes:
  db-data:
    driver: local

networks:
  library:
    driver: bridge