services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: library-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library-db
    ports:
      - "5455:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - library

  redis:
    image: redis:alpine
    container_name: library-redis
    ports:
      - "6379:6379"
    networks:
      - library

  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: library-node
    container_name: library-node
    command: npm run migrate && npm run seeder category
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - library
    env_file:
      - .env
    ports:
      - "3333:3333"

volumes:
  db-data:
    driver: local

networks:
  library:
    driver: bridge